FROM ubuntu:14.04

RUN apt-get update \
    && apt-get install -y apache2 \
    && apt-get install -y php5 libapache2-mod-php5 \
    && apt-get install -y php5-mysql php5-sqlite php5-tidy php5-gd \
    && apt-get install -y mysql-server \
    && apt-get install -y mysql-client \
    && apt-get install -y unzip curl

COPY src/bWAPP_latest.zip /var/www/html/
COPY src/index.html /var/www/html/

COPY start.sh /start.sh

RUN chmod 700 /start.sh

EXPOSE 80

CMD ["/start.sh"]

